---
on: [pull_request] #  yamllint disable-line rule:truthy
name: main
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm install --save-dev @commitlint/{config-conventional,cli}
      - run: npx commitlint --from=${{ github.event.pull_request.base.sha }}

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3

  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile
